<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701164841 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create customer table with identifiers starting at 100000';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE customer (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(20) NOT NULL,
                surname VARCHAR(20) NOT NULL,
                PRIMARY KEY (id)
            )'
        );
        $this->addSql('ALTER TABLE customer ALTER COLUMN id RESTART WITH 100000');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE customer');
    }
}
