<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701171434 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create book_loan table with book and customer relations';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE book_loan (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              borrowed_at DATE NOT NULL DEFAULT CURRENT_DATE,
              returned_at DATE DEFAULT NULL,
              book_id INT NOT NULL,
              customer_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_DC4E460B16A2B381 ON book_loan (book_id)');
        $this->addSql('CREATE INDEX IDX_DC4E460B9395C3F3 ON book_loan (customer_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              book_loan
            ADD
              CONSTRAINT FK_DC4E460B16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              book_loan
            ADD
              CONSTRAINT FK_DC4E460B9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE book_loan DROP CONSTRAINT FK_DC4E460B16A2B381');
        $this->addSql('ALTER TABLE book_loan DROP CONSTRAINT FK_DC4E460B9395C3F3');
        $this->addSql('DROP TABLE book_loan');
    }
}
