<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701165602 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create author table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE author (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(20) NOT NULL,
                surname VARCHAR(20) NOT NULL,
                PRIMARY KEY (id)
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE author');
    }
}
