<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701170246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create book table with required author relation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE book (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                author_id INT NOT NULL,
                title VARCHAR(50) NOT NULL,
                PRIMARY KEY (id)
            )'
        );
        $this->addSql('CREATE INDEX IDX_CBE5A331F675F31B ON book (author_id)');
        $this->addSql(
            'ALTER TABLE book
            ADD CONSTRAINT FK_CBE5A331F675F31B
            FOREIGN KEY (author_id) REFERENCES author (id)
            ON DELETE RESTRICT
            NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
        $this->addSql('ALTER TABLE book ALTER COLUMN id RESTART WITH 100000');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE book');
    }
}
